name:               data-cmd
version:            0.1.0.0
license:            NONE
author:             Vito Canadi
maintainer:         vito.canadi@gmail.com
extra-source-files: CHANGELOG.md
synopsis:           Parser and renderer for any(generic) type. Suitable for command line, textual represenation of the type
ghc-options:
  -fconstraint-solver-iterations=10

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - DefaultSignatures
  - ScopedTypeVariables
  - TypeApplications
  - DeriveGeneric

dependencies:
  - base
  - QuickCheck
  - generic-arbitrary

library:
  source-dirs: src

tests:
  spec:
    build-depends:
    - data-cmd
    - base
    - hspec
    - QuickCheck
    - generic-arbitrary
    main: Spec.hs
    source-dirs: spec
version: 0.1.0.0
